version: '3.8'

networks:
    snappfood-network:
        driver: bridge

services:
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: yuor_password
            MYSQL_DATABASE: snappfood
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - snappfood-network

    laravel-app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: snappfood
            DB_USERNAME: root
            DB_PASSWORD: your_password
        command: bash -c "php artisan test && php artisan install-command && php-fpm"
        depends_on:
            - mysql
        networks:
            - snappfood-network

    nginx:
        image: nginx:latest
        ports:
            - "9000:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - laravel-app
        networks:
            - snappfood-network

volumes:
    mysql_data:
